loglevel: info

app:
  addr: 0.0.0.0:8080

auth:
  addr: 0.0.0.0:8082
  env:
    dev:
      extaddr: auth:8082
      dburl: postgres://amicie:admin@authdb:5432/ppc_auth?sslmode=disable
    test:
      extaddr: localhost:8082
      dburl: postgres://amicie:admin@localhost:5432/ppc_auth?sslmode=disable
    
profile:
  addr: 0.0.0.0:8084
  env:
    dev:
      extaddr: profile:8084
      dburl: postgres://amicie:admin@profiledb:5432/ppc_profile?sslmode=disable
    test:
      extaddr: localhost:8084
      dburl: postgres://amicie:admin@localhost:5432/ppc_profile?sslmode=disable
