package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"
	"fmt"
	"pawpawchat/generated/graphgen"
)

// UserBiography is the resolver for the userBiography field.
func (r *mutationResolver) UserBiography(ctx context.Context, id string, changes graphgen.UserBiographyInput) (*graphgen.User, error) {
	panic(fmt.Errorf("not implemented: UserBiography - userBiography"))
}

// Mutation returns graphgen.MutationResolver implementation.
func (r *Resolver) Mutation() graphgen.MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }
