FROM golang:1.22

WORKDIR /auth

RUN apt-get update && apt-get install -y \
    bash \
    git \
    postgresql-client \
    && rm -rf /var/lib/apt/lists/*
    

COPY . .

RUN go mod tidy
RUN go build -o main ./cmd/auth/main.go

EXPOSE ${AUTH_PORT}

CMD ["./main"]


