FROM golang:1.22

RUN apt-get update && apt-get install -y \
    bash \
    git \
    postgresql-client \
    && rm -rf /var/lib/apt/lists/* 

WORKDIR /profile

COPY . .

RUN go mod tidy
RUN go build -o main cmd/profile/main.go

EXPOSE ${PROFILE_PORT}

CMD ["./main"]